### PR TITLE
feat: add account export API endpoint

### PR DESCRIPTION
**Pull request by 0marSalah**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new POST endpoint for account export requests.
	- The endpoint responds with a confirmation and a 200 status code.

### CODE REVIEW

**Comment by dahlia** [comment]
Does Mastodon actually this API as well? I can't find any related section in [their docs](https://docs.joinmastodon.org/methods/).

**Comment by 0marSalah** [comment]
it does provide export functionality through the web UI, https://mastodon.social/settings/export

**Comment by dahlia** [comment]
I'm sorry, but I don't see the point of this PR, as it doesn't actually implement the logic to export. If it's not reviewable now, please turn it into a draft.

**Comment by 0marSalah** [comment]
You're absolutely right—the endpoint should have some functionality, but due to [this issue](https://github.com/did-coop/activitypub-export/issues/1), I couldn’t find any specific requirements for the response other than returning a 200 status. Would you suggest returning all account data, or is there a different expected behavior? In any case, I'll turn this into a draft and await Dmitri's input.

**Comment by dahlia** [comment]
The link you gave me is showing a 404.

**Comment by dmitrizagidulin** [comment]
@dahlia deep apologies, this PR was made to the wrong fork. Please feel free to close it.

In case you're curious about what we're working on, we're implementing [FEP-9091: Account Export Service Endopint](https://codeberg.org/fediverse/fep/src/branch/main/fep/9091/fep-9091.md) and [FEP-6fcd: Account Export Container Format](https://codeberg.org/fediverse/fep/src/branch/main/fep/6fcd/fep-6fcd.md).

This PR was just a small first step (of adding the export endpoint, and in subsequent PRs we'll add the functionality to actually export the Actor profile, their activities, etc).

We were planning to ping you after it was completed, to see if you were interested in that feature upstream in this Hollo repo.

If you'd like to keep an eye on how it's progressing (and give code feedback etc), we can make PRs against something like a feature breanch, `account-export`? Mostly didn't want to bother you.

Thanks again for a great project.

**Comment by dmitrizagidulin** [comment]
@dahlia also I just fixed the visibility on the 404 link, should be visible now.

**Comment by dahlia** [comment]
@dmitrizagidulin Thanks for explanation! I got it now.  To implement [FEP-9091](https://w3id.org/fep/9091), you probably want Fedify to have the `Export` class.  I'm going to work on it soon.

**Comment by dahlia** [comment]
I filed an issue for it to the Fedify repository: <https://github.com/dahlia/fedify/issues/146>.

**Comment by dmitrizagidulin** [comment]
> I filed an issue for it to the Fedify repository: [dahlia/fedify#146](https://github.com/dahlia/fedify/issues/146).

Wow, hahahah, that was fast! :) Thank you so much!

**Comment by dmitrizagidulin** [comment]
@dahlia feel free to close this PR.

**Pull request closed without merging**
